name: Nix Flake actions

on:
  pull_request:
  push:
#    branches:
#      - master
#      - main

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Check Flake
        run: nix flake check

